Feature/#94 motor group drivetrain
NorthernForce/ChargedUp pull request #102
Opened 2023-02-25 21:52 UTC by FRCTeam172

2023-02-25 21:58 UTC, cml1010101 approved these changes

2023-02-25 22:31 UTC, cml1010101 requested changes

2023-02-25 22:31 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/variants/MotorGroupTalon.java
>      }
you need to invert the encoder rotations if necessary (if inverted)

2023-02-25 22:36 UTC, cml1010101 requested changes

2023-02-25 22:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    return 0;
should return the distance traveled. This is vital.

2023-02-25 22:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    return new DifferentialDriveWheelSpeeds(0,0);
should return speeds. this is vital

2023-02-25 22:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    return 0;
should return right distance. This is vital

2023-02-27 20:44 UTC, cml1010101 approved these changes

2023-03-01 17:21 UTC, cml1010101 requested changes
Just a minor change

2023-03-01 17:21 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +   * Drives using feet per second
Should be meters per second.

2023-03-01 22:04 UTC, tagnihotri requested changes
I think it might flow better if there are some addition comments added to explain other lines of code. (Saihaj is in agreement with this statement)

2023-03-01 22:07 UTC, cml1010101 approved these changes

2023-03-01 23:38 UTC, christianr-172 approved these changes
Looks good
:)

2023-03-01 23:38 UTC, tagnihotri approved these changes
Good

2023-03-01 23:40 UTC, merged