Feature/arm setpoints
NorthernForce/ChargedUp pull request #283
Opened 2023-03-23 14:53 UTC by cml1010101

2023-03-23 22:33 UTC, skohli2026 approved these changes

2023-03-23 23:09 UTC, FRCTeam172 requested changes
Change this to be bumper, forwards, vertical, backwards or something similar. 
Low, mid, high could be confused with grid angles.

2023-03-24 02:14 UTC, tagnihotri approved these changes

2023-03-30 23:11 UTC, FRCTeam172 commented
Setting the arm and wrist angles can take parameters in OI. This should do that instead of having multiple different commands!

2023-03-31 01:29 UTC, merged