Feature/limelight auto align on manipulator a
NorthernForce/ChargedUp pull request #284
Opened 2023-03-23 15:00 UTC by cml1010101

2023-03-23 22:25 UTC, skohli2026 approved these changes

2023-03-23 23:27 UTC, FRCTeam172 requested changes
Did we talk to the drive team about where this should be mapped? I feel like it makes more sense on the driver controller personally.

2023-03-24 02:03 UTC, tagnihotri commented
> Did we talk to the drive team about where this should be mapped? I feel like it makes more sense on the driver controller personally.

Why is it that we don't put it on both, unless it causes distraught to the drive team, it might benefit the driver and manipulator both

2023-03-24 02:05 UTC, tagnihotri requested changes
I agree with Trevin. Lets check with the drive team about this

2023-03-30 00:10 UTC, tagnihotri approved these changes

2023-04-01 00:44 UTC, FRCTeam172 approved these changes

2023-04-01 00:44 UTC, merged