Fixes a really boring issue we had in code, dont really need to
NorthernForce/ChargedUp pull request #294
Opened 2023-03-25 13:45 UTC by christianr-172

inspect closely.

2023-03-25 13:58 UTC, ehunthawkins approved these changes

2023-03-27 00:18 UTC, tagnihotri approved these changes

2023-03-30 01:20 UTC, cml1010101 requested changes
We need to figure out why this doesn't work.

2023-03-30 01:39 UTC, cml1010101 approved these changes

2023-03-30 01:44 UTC, cml1010101 approved these changes

2023-04-03 00:19 UTC, merged